### ISSUE TITLE
Understand how appropriate bodies sign in the current AB portal and decide how sign in will work for its replacement

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#362] opened 2024-09-26 14:36 UTC
## Why?
Early on, we looked at how appropriate bodies accessed DfE services.

We found out:
- the AB portal and Check a teacher's record both use DfE Sign in
- it was very confusing understanding how they were given access to both
- appropriate bodies are not reliably represented in DFE sign in data, for example, there is not a unique identifier they share  for us to know that each organisation **is** an appropriate body
- Steve (old dev) used to work on Check a teacher's record and says they set up a manual way to send lists to DFE Sign in to know organisation types for authorisation, but this was time-consuming and took some time to work out
- there seemed to be some sort of method where a list of ABs was sent to DFE sign in to try and get DfE Sign in to work better, perhaps letting them know exactly what organisations were allowed access to the service
- there aren't particular painpoints with ABs accessing the current ECF1 service Check data for appropriate bodies

What was quite key is that we never got to the bottom of how users are added to the AB portal. We know they use DfE Sign in, but not if:
ABs use DfE sign in and can self-serve their onboarding to the AB portal, and can sort out their DfE Sign in access themselves (potentially dependent on the TRA teams sending over lists of ABs to the DFE Sign in team)
OR
ABs use DfE sign in and cannot self-serve, but need to ask TRA for each user to be added to the appropriate body to access the AB portal

Similarly, we didn't work out if appropriate bodies can add new users once they have 1 user onboarded for their organisation.

Because we were only planning to replace Check data for ABs at the time, we just decided for ABs we would not use DfE sign in for authorisation for MVP. We would just use it for authentication - and offer the option of email sign in links as well.

However, given we are now replacing the AB Portal as well, this might be worth reconsidering. 

## What?
- Work out how as-is access to the AB portal works
- Decide how we want to handle AB access to the new service to submit induction information
- Consider follow up tickets to get this done, e.g. contacting the DFE Sign in team to get everything set up

## Helpful links or other information
[Design history we wrote](https://teacher-cpd.design-history.education.gov.uk/ecf-v2/exploring-using-dfe-sign-in/)

Similar tickets:
https://github.com/orgs/DFE-Digital/projects/48/views/10?filterQuery=DfE+sign&pane=issue&itemId=72698443
https://github.com/orgs/DFE-Digital/projects/48/views/10?filterQuery=DfE+sign&pane=issue&itemId=71426566

**Comment by kas-madrigal** [comment] 2024-10-02 13:42
@claire-hughez who do we speak to in regards to getting access to the `Manage DFE Sign in console`??

**Comment by kas-madrigal** [comment] 2024-10-02 13:47
Working progress of research https://lucid.app/lucidspark/17be7960-2487-4c49-bdb6-15c144f8c2fb/edit?view_items=_afeY54c2djr&invitationId=inv_8fa9969b-e457-4912-b015-1ada6a848ff1

**Comment by gracecbrennan** [comment] 2024-10-03 08:49
Call scheduled with DfE sign-in team nxt week

**Comment by kas-madrigal** [comment] 2024-10-07 14:56
Please [view the full call here](https://educationgovuk-my.sharepoint.com/:v:/r/personal/kas_madrigal_education_gov_uk/Documents/Recordings/Appropriate%20Body%20DfE%20sign%20in-20241007_150211-Meeting%20Recording.mp4?csf=1&web=1&e=l7Uk8N&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D)

**Summary** 
In the as-is DfE sign in (Jane L. and Ilona) receive a csv from TRA with the hard-coded list of ABs that can have access to the AB portal. ABs in CPD use a single sign in link and all the information on the organisations and users relationship to them is stored in the CPD database. **@peteryates this is a change database wise, what are your thoughts?** 

The CSV rarely has any changes but when it does the process to provide the CSV is the following:

Step 1 - Dfe intranet
![Image](https://github.com/user-attachments/assets/db622f21-98f9-4472-a945-f389063a42d3)

Step 2 - Dfe sign in
![Image](https://github.com/user-attachments/assets/4129c60f-42e8-4dc4-95c7-2d89584ffeed)

Step 3 - form
![Image](https://github.com/user-attachments/assets/0fcab349-ab0f-4954-b26e-20a672c7cfff)

Step 4 - change existing service
![Image](https://github.com/user-attachments/assets/ecea6144-0078-4615-a79a-5205c6335a70)

Step 5 - add attachments
![Image](https://github.com/user-attachments/assets/608d8165-ef1c-4a65-ab6c-5ba5072b1e27)

> It is the same process to `onboard a new service` (decommission the AB portal on TRA and connect the AB portal in CPD) but in the dropdown you click 'onboard a new service'. 

Support team on TRA side have also access to the Manage access service that allows them to review users but if any changes need to be made they ask that of DfE signin team. 

Next steps
- There's no specific data migration that needs to happen as when we go through the formal 'onboard a new service' request the data will be migrated by DfE sign in.
- Once we make this request the corresponding dev teams will speak to each other in order to make that as easy as possible
- Kas/Emily need to speak to TRA around their internal processes to provide the CSV list of AB portal users to DfE sign in (have messaged Komal) 
**- Pete to review this process and give his opinion on best way to manage it with DfE sign in**

**Comment by kas-madrigal** [comment] 2024-10-08 08:14
@peteryates could you review that last comment when you get a chance?

**Comment by peteryates** [comment] 2024-10-08 09:43
I had a chat with @gunndabad this morning and his response might have thrown a spanner in these works 🔧 

> The way is works at the moment is a little... convoluted. There's a SOAP service in the DQT infrastructure that gets pushed user and org updates from DSI. This service writes those changes to CRM. When a user signs in, the AB Portal calls the DSI API to get some more information about the user and org then looks up the corresponding records in DQT.

This sounds like an awful lot of complexity and it's not really using DfE sign-in to its strength.

**Comment by gracecbrennan** [comment] 2024-10-11 08:47
To check-in with Pete on Monday

**Comment by peteryates** [comment] 2024-10-11 15:01
So I've been chatting quite a bit with one of the DfE Sign-in devs and believe I've outlined the login process we need to use in #453 

There are some assumptions in that issue that need to be confirmed *but* it's sounding like the SOAP thing I mentioned above was the best solution in 2018/19 but no longer is, and the API can tell us what we need.

However, this means that:

* we need a common identifier in our list of appropriate bodies that we can link to appropriate bodies in DfE Sign-in (probably the DfE Sign-in `organisation.id`)
* we won't need to keep and manage a list of AB users, DfE Sign-in will take care of all that
* we'll be able to add new ABs automatically when their users come to us from DfE Sign-in (this could be a source of pain too, we need to dig into it)

**Comment by claire-hughez** [comment] 2024-10-16 08:46
@emily-prudence-dfe to review

**Comment by emily-prudence-dfe** [comment] 2024-10-16 10:20
Hi @JaredAMarsh 

Thanks so much for your help on this.

Pete has taken me through what you've discussed so far. We know there's an `appropriate body` user type; I just wanted to check that this would be available to **all** appropriate body users, including those associated with appropriate bodies which are not Teaching School Hubs.

For context, most appropriate bodies are Teaching School Hubs (TSHs), but there are a handful of other select organisations (e.g. The Independent Schools Teacher Induction Panel (ISTIP) who assure ~1000 inductions per year for independent schools) who can also act as appropriate bodies. We need users from all appropriate bodies to be able to sign into our service; I just want to make sure we're not tripped up by assuming they're all covered and it turns out to be tricky for non-TSH users.

Thanks!

**Comment by gracecbrennan** [comment] 2024-10-23 08:53
@peteryates can we discuss and agree way to chase Jared?

**Comment by JaredAMarsh** [comment] 2024-10-23 10:13
@emily-prudence-dfe @peteryates I do apologise for not getting to this sooner, I didn't even get an email or any notification for your mention so I'm sorry about that 😄 I will check my GitHub notification settings in case I've turned anything off 👍

Easiest way to chase/get hold of me is through Slack, or Teams (though Teams notifications are sometimes a pain 😅)

---

So for the "Teacher Services - Appropriate Body" service on DfE Sign-in, we currently have a list of **288 organisations** who can request access to it and the role within it, so long as they are Open/Proposed to Close. This list will have been updated through ServiceNow service requests from the current AB team over time to add/remove organisation when needed.

I'm happy to send that list to whoever needs it in order to check the validity of it and to ensure any organisations that are needed get added 😄 If someone could make a ServiceNow request for it under `DfE Service Catalog > DfE Sign-in > DfE Sign-in requests` with the request type of "Other" it'll be tracked on our side 👍 

The SOAP integration is _slightly_ separate, that is how AB as well as the other DQT Employer Access services receive any of the following to go into your CRMs:

- Organisation additions/updates: These run every morning once we receive new org data from GIAS/PIMS, as well as a manual sync we can do on an ad-hoc basis.
- User additions/updates: User status, name or email updates if they already have access to the service, or a record is created if they add the service to themselves for the first time. This can also be run manually per-user on an ad-hoc basis.

I unfortunately don't know for certain how that data gets used across each of the DQT services, or what CRMs it gets filtered into. You're also not required to use it if you get your data from somewhere else, our organisation data comes from the Provider Profile team 👍

When a user logs into the service I assume there is currently a check against the CRM to see if that organisation and possibly user exist so you can retrieve the data. An alternative way of doing this would be when you get the user's OIDC claims including their sub/user ID, and their chosen organisation ID, a request can go to our public API to make sure they have the service and role assigned to their account before they are allowed access to the AB application (obviously if you have the org data on your side), so we're managing that access list and you can just check against it on login.

I hope I answered all the questions (I do like to waffle sometimes 😆) so if I haven't please let me know, and I'm also happy to hop on calls when schedules permit to go through anything or explain anything needed 👍 The DSi team's job is to try and make this transition as smooth as we can 😄

**Comment by gunndabad** [comment] 2024-10-23 10:31
>When a user logs into the service I assume there is currently a check against the CRM to see if that organisation and possibly user exist so you can retrieve the data.

That's how it works today; there's some additional metadata stored on the corresponding CRM records that is required to make the legacy portals work (e.g. the 'is appropriate body' flag held against the organisation record).

**Comment by claire-hughez** [comment] 2024-10-25 08:43
Will move this to done. Plan to use DFE Sign in. Will add analysis ticket for next sprint goals.

**Closed** 2024-10-25 08:43 UTC
